### ISSUE TITLE
install libDmet

### ISSUE THREAD

**Issue by Jila66** [gkclab/libdmet_preview#1]
How to install it?

**Comment by zhcui** [comment]
Hi,

First, install pyscf, following: https://pyscf.org/install.html

Then, create a directory on your computer, e.g., 
mkdir ~/libdmet
cd ~/libdmet
git clone https://github.com/gkclab/libdmet_preview .
export PYTHONPATH=~/libdmet_preview:$PYTHONPATH

**Comment by Jila66** [comment]
Hi,

Thanks. 
yes, I did it but it doesn't work.

**Comment by zhcui** [comment]
Please attached the information you get.

**Comment by Jila66** [comment]
I install PyScf and it works.

Then, as you said
create a directory on my computer 
get the libdmet code by git clone command ( didn't install )
add a libdmet directory to my  pythonpath

But when I test an example code that use libdmet module , 
it gives the following error: 
Module Not Found Error: No module named 'libdmet'

**Comment by zhcui** [comment]
You don't need to install it, since it is a pure python based program.

**Comment by Jila66** [comment]
Yes, 
But I don't now why it doesn't work for me

**Comment by zhcui** [comment]
Try print out the following:
`echo $PYTHONPATH`

**Comment by Jila66** [comment]
The result is :
/home/jila/libdmet:

**Comment by Jila66** [comment]
Zhi Hao, Thank you for your patience in responding.

I upgrade and then, remove all pyscf and install it again and get the libdmet cod too.
Now it works.

Maybe there is an error in my system Prerequisites.
