### ISSUE TITLE
Wrong result in the third example "03-dmet-nio-afm" 

### ISSUE THREAD

**Issue by Jila66** [gkclab/libdmet_preview#14]
Hi,

When I run the third example "03-dmet-nio-afm", in the DMET part we have a number electrons alpha and beta.
We know by using pseudo potential we have 18 and 6 electrons for Ni and O respectively. So in a unit cell of NiO ( 2 Ni and 2 O ) we have 48 electrons that in AFM phase number of alpha and beta electrons are 24.

But in the output file of this example it's not true. 
**The result line : number electrons alpha = 28  beta = 28** ( _If necessary I can send the output file._ )

If I'm wrong please correct me.

**Comment by zhcui** [comment]
There are 28 valence orbitals, 50 virtual orbitals. The number of embedding electrons equals to the 2 * nval = 56 (28 alpha, 28 beta).

**Comment by Jila66** [comment]
Yes, Your are right. That's the embedding electrons.
Thanks ,
