### ISSUE TITLE
Is ther any way te restart DMET calculation?

### ISSUE THREAD

**Issue by Jila66** [gkclab/libdmet_preview#16]
Hi,

I know there is no restart mechanism available in PySCF package. But it can be “restarted” by the proper initial guess. 
Is there any same trick for the DMET calculation too?

Thanks

**Comment by zhcui** [comment]
You can save the parameters of correlation potential by
`np.save("vcor_param.npy", vcor.param)`

and load it by
```
vcor_param = np.load("vcor_param.npy") 
vcor.update(vcor_param)
```

**Comment by Jila66** [comment]
Many thanks,
