### ISSUE TITLE
printout level of `__doc__` and info about Wannier90

### ISSUE THREAD

**Issue by mcocdawc** [gkclab/libdmet_preview#22]
May I ask if the printout level of
```python
section("%s", libdmet.__doc__)
```
```python
    log.info("wannier90 library path not set or incorrectly.")
```

could be perhaps reduced to something below `INFO`?
It adds a bit of unnecessary clutter if `libdmet`  always starts printing just by importing it.

**Comment by zhcui** [comment]
I agree

**Comment by mcocdawc** [comment]
does that mean you will change it yourself, or shall I open a PR?

**Comment by zhcui** [comment]
I made the change

**Comment by mcocdawc** [comment]
Thank you

**Comment by mcocdawc** [comment]
I just checked and the printout of `section("%s", libdmet.__doc__)` is still there, which means it is still printing upon importing. :-(

**Comment by cariluo** [comment]
Gently bumping this.
