### ISSUE TITLE
pyscf.lib.map_with_prefetch seems not supported at least for PySCF 1.7.5

### ISSUE THREAD

**Issue by ywlds** [gkclab/libdmet_preview#7]
@zhcui 
It seems the requirement for PySCF should be >1.75. I test with PySCF 2.0.0  to test the sample code 
of NiO-AFM.py. Seems ok. 

I check and notice you update this part by removing the "restart" key in solver_args. I also notice this during my test.
so modify to : solver_args = {"nelec": (Lat.ncore+Lat.nval)*2, "dm0": dmet.foldRho_k(rho_k, basis_k)}.

Many thanks.

**Comment by ywlds** [comment]
@zhcui

**Comment by zhcui** [comment]
Thanks. The README is updated. PySCF 2.0 should work well.
